FROM ghcr.io/graalvm/native-image-community:25 AS graalvm

COPY . /home/app/demo
WORKDIR /home/app/demo

RUN native-image -cp target/demo-*-all.jar -o demo

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=graalvm /home/app/demo/demo /app/demo
ENTRYPOINT ["/app/demo"]
