FROM ghcr.io/graalvm/native-image-community:25 AS build
WORKDIR /app
COPY .mvn .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:resolve -q
COPY src src
RUN ./mvnw package -DskipTests -q
RUN native-image -cp target/demo-*.jar -H:Class=com.example.Application -o demo

FROM frolvlad/alpine-glibc
RUN apk update && apk add libstdc++
EXPOSE 8080
COPY --from=build /app/demo /app/demo
ENTRYPOINT ["/app/demo"]
